// agw-eoa-linking/src/app/page.tsx
"use client";

import Image from "next/image";
import { useAccount } from "wagmi";
import { BackgroundEffects } from "@/components/ui/BackgroundEffects";
import { ResourceCards } from "@/components/ui/ResourceCards";
import { ConnectedState } from "@/components/wallet/ConnectedState";
import { SignInButton } from "@/components/wallet/SignInButton";

export default function Home() {
  const { address } = useAccount();

  return (
    <div className="relative grid grid-rows-[1fr_auto] min-h-screen p-8 pb-20 sm:p-20 font-[family-name:var(--font-avenue-mono)] bg-black overflow-hidden">
      <BackgroundEffects />

      <main className="relative flex flex-col items-center justify-center z-10 text-white text-center">
        <div className="flex flex-col items-center gap-8">
          <Image
            src="/abstract.svg"
            alt="Abstract logo"
            width={240}
            height={32}
            quality={100}
            priority
          />
          <p className="text-md font-[family-name:var(--font-roobert)]">
            Get started by editing{" "}
            <code className="bg-white/[.06] px-1 py-0.5 rounded font-semibold">
              src/app/page.tsx
            </code>
            .
          </p>

          {address ? <ConnectedState /> : <SignInButton />}
        </div>
      </main>

      <ResourceCards />
    </div>
  );
}

// agw-vue/src/App.vue
<script setup lang="ts">
import { useWallet } from './composables/useWallet'
import WalletConnect from './components/WalletConnect.vue'
import ConnectedWallet from './components/ConnectedWallet.vue'
import BackgroundEffects from './components/BackgroundEffects.vue'
import ResourceCards from './components/ResourceCards.vue'

const { address } = useWallet()
</script>

<template>
  <div class="relative grid grid-rows-[1fr_auto] min-h-screen p-8 pb-20 sm:p-20 bg-black overflow-hidden" style="font-family: var(--font-avenue-mono)">
    <BackgroundEffects />

    <main class="relative flex flex-col items-center justify-center z-10 text-white text-center">
      <div class="flex flex-col items-center gap-8">
        <img
          src="/abstract.svg"
          alt="Abstract logo"
          width="240"
          height="32"
          class="quality-100 priority"
        />
        <p class="text-md" style="font-family: var(--font-roobert)">
          Get started by editing 
          <code class="bg-white/[.06] px-1 py-0.5 rounded font-semibold">
            src/App.vue
          </code>
          .
        </p>

        <ConnectedWallet v-if="address" />
        <WalletConnect v-else />
      </div>
    </main>

    <ResourceCards />
  </div>
</template>
